<a href="https://colab.research.google.com/github/tsPRIYANKA/Internship/blob/master/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
>>> import numpy as np
>>> a = np.arange(20).reshape(1,4,5)
>>> a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [0]:
a.shape

(8, 5)

In [0]:
a.ndim

3

In [0]:
a.dtype

dtype('int64')

In [0]:
a.data

In [0]:
a.size

20

In [0]:
>>> import numpy as np
>>> s = np.array([3,1,8])
>>> s

array([3, 1, 8])

In [0]:
s.data

In [0]:
s.dtype

dtype('int64')

In [0]:
p=np.array([8,3,1])
p

array([8, 3, 1])

In [0]:
b = np.array([(1,2,3), (4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
b.dtype

dtype('int64')

In [0]:
b.ndim

2

In [0]:
y=np.array([[1,3],[4,5]],dtype=complex)
y

array([[1.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j]])

In [0]:
e=np.zeros((3,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
g=np.ones((2,3))
g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.empty((4,3))


array([[3.34108217e-316, 2.37663529e-312, 2.14321575e-312],
       [2.37663529e-312, 2.56761491e-312, 8.48798317e-313],
       [9.33678148e-313, 8.70018275e-313, 2.12199579e-313],
       [2.12199580e-313, 5.53353523e-322, 0.00000000e+000]])

In [0]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [0]:
np.arange( 0, 2, 0.3 )  

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [0]:
from numpy import pi
>>> np.linspace( 0, 2, 9 ) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [0]:
x = np.linspace( 0, 2*pi, 5 )       
>>> f = np.sin(x)
f

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [0]:
m=np.arange(8)   #printing arrays
print(m)

[0 1 2 3 4 5 6 7]


In [0]:
u=np.arange(15).reshape(5,3)      #2d array
u

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
 c = np.arange(24).reshape(2,3,4)         # 3d array
>>> print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [0]:
h=print(np.arange(31))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [0]:
t=print(np.arange(100).reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [0]:
y=np.arange(8)
y

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
>>> ai = np.array( [20,30,40,50] )
>>> cb = np.arange( 4 )
>>> cb


array([0, 1, 2, 3])

In [0]:
v=ai-cb
v

array([20, 29, 38, 47])

In [0]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A * B              

array([[2, 0],
       [0, 4]])

In [0]:
S=np.array([[6,5],[8,0]])
K=np.array([[7,5],[5,3]])
S@K

array([[67, 45],
       [56, 40]])

In [0]:
S.dot(K)

array([[67, 45],
       [56, 40]])

In [0]:
import numpy as np
a = np.ones((2,3), dtype=int)
b=np.random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [0]:
b += a
b

array([[3.15542137, 3.66135469, 3.85844328],
       [3.70403264, 3.82654693, 3.98577451]])

In [0]:
import numpy as np
from numpy import pi
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name


'float64'

In [0]:
c=a+b
c

array([1.        , 2.57079633, 4.14159265])

In [0]:
c.dtype.name

'float64'

In [0]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [0]:
d.dtype.name

'complex128'

In [0]:
a = np.random.random((2,3))
a

array([[0.53629839, 0.04480441, 0.1219503 ],
       [0.40929449, 0.6037987 , 0.07808076]])

In [0]:
a.sum()

1.7942270417442785

In [0]:
a.min()

0.04480440735564195

In [0]:
a.max()

0.6037986965990425

In [0]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
 b.sum(axis=0)  #sum of each column

array([12, 15, 18, 21])

In [0]:
b.min(axis=1)  #min of each row

array([0, 4, 8])

In [0]:
b.cumsum(axis=1)              #cumulative sum along each row           

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [0]:
B = np.arange(3)
B

array([0, 1, 2])

In [0]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [0]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [0]:
# indexing and slicing
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [0]:
a[2]

8

In [0]:
a[2:5]

array([ 8, 27, 64])

In [0]:
a[-1]

729

In [0]:
a[:6:2]

array([ 0,  8, 64])

In [0]:
a[:6:2] = -318
a

array([-318,    1, -318,   27, -318,  125,  216,  343,  512,  729])

In [0]:
a[ : :-3]
    

array([ 729,  216,   27, -318])

In [0]:
for i in a:
  print(i)

-318
1
-318
27
-318
125
216
343
512
729


In [0]:
def f(a,b):
  return 10*a+b
p = np.fromfunction(f,(5,4),dtype=int)
p

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
p[3:5]

array([[30, 31, 32, 33],
       [40, 41, 42, 43]])

In [0]:
G=np.array(8)
G

array(8)

In [0]:
x = np.array([[ 1,  2,  3,  4],
    [ 5,  6,  7,  8],  [ 9, 10, 11, 12]])

x.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [0]:
x.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [0]:
x.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [0]:
a = np.floor(10*np.random.random((3,4)))
a

array([[9., 2., 7., 2.],
       [9., 3., 6., 2.],
       [9., 4., 1., 5.]])

In [0]:
import numpy as np
a = np.arange(12)
b = a            #copying
b  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
import numpy as np
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [0]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [0]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
u = np.eye(4)         #eye(identity matrix)
u

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
j=np.array([[0,-1],[1,0]])
j

array([[ 0, -1],
       [ 1,  0]])

In [12]:
j@j

array([[-1,  0],
       [ 0, -1]])

In [13]:
np.trace(u)

4.0

In [15]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))